### ISSUE TITLE
rna-seq-workflow should copy all annotations

### ISSUE THREAD

**Issue by allaway** [sgosline/NEXUS#5]
With the exception of ones that it is changing or making irrelevant, like "fileFormat" = .sf and "readPair"

**Comment by sgosline** [comment]
So there's an option to do this by the second clinical query, are there specific annotations we should add?

**Comment by allaway** [comment]
Sorry, I don't understand. I am suggesting we copy all annotations over from fastqs processed with this pipeline to the output quant.sf files that are returned to Synapse.

**Comment by sgosline** [comment]
So we essentially do that already by the `sample_query` parameter - any annotations you want to pass along you put into this query, and it will ensure they are applied to the uploaded folder.  I'm afraid of trying to do this automatically.

**Comment by allaway** [comment]
Oh, interesting, that makes a lot more sense. I was missing a bunch of
annotations on the NF2 quant.sf files, and I wasn't sure why.
